# Generated by Django 4.2.6 on 2023-10-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_id', models.CharField(max_length=15)),
                ('Player_name', models.CharField(max_length=30)),
                ('Event', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=20)),
                ('Age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
